micronaut:
  server:
    max-request-size: '100MB'
    multipart:
      max-file-size: '100MB'
    port: 8080

greenlight:
  db:
    mongo:
      host: "enthusiast-greenlight.mongo.cosmos.azure.com"
      port: 10255
      username: "enthusiast-greenlight"
      password: "${MONGO_PASSWORD}"
    rogan:
      bot-token: "${ROGAN_TOKEN}"
